### ISSUE TITLE
Code Length Detection

### ISSUE THREAD

**Issue by fschuermeyer** [hellocodingDE/hellocoding-bot#7]
**Is your feature request related to a problem? Please describe.**
If a User write Code over 2000 Chars - the Bot will Delete the Message and Send a Message to the User the Text is to long - to use pasebin or something else. This Behaviour only works if inside the Message is Programming Code.

**Comment by uvulpos** [comment]
done  -> commit #9 ->27e25c614030a0c5345690cc1b9e1312345745d4
